PWADemo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('polls/', include('polls.urls'))
]

home/urls.py
from django.urls import include, path
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('sw.js', views.ServiceWorkerView.as_view(), name=views.ServiceWorkerView.name),
    path('offline', views.offline, name='offline'),
    path('favicon.ico', views.favicon, name='favicon')
]

polls/urls.py
from django.contrib import admin
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote')
]

home/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

home/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render
from django.views.generic import TemplateView

from os import path

from PWADemo.settings import VERSION, BASE_DIR

# Create your views here.

def index(request):
    return render(request, 'home/index.html')


class ServiceWorkerView(TemplateView):
    template_name = 'sw.js'
    content_type = 'application/javascript'
    name = 'service_worker'

    def get_context_data(self, **kwargs):
        return {'VERSION': VERSION}


def offline(request):
    return render(request, 'home/index.html')


def favicon(request):
    file_path = path.join(BASE_DIR, 'home/static/home/img/favicon.ico')
    try:
        with open(file_path, 'rb') as icon_file:
            response = HttpResponse(icon_file.read(), content_type='image/vnd.microsoft.icon')
            return response
    except:
        return Http404()

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.template import loader
from django.shortcuts import render

from .models import Question

# Create your views here.

def index(request):
    question_list = Question.objects.all()[:10]
    template = loader.get_template('polls/index.html')
    context = {
        'question_list': question_list
    }
    return HttpResponse(template.render(context, request))


def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404('Question doesn\'t exist.')
    return render(request, 'polls/details.html', {'question': question})


def results(request, question_id):
    return HttpResponse('You are looking at the results of question %s.' % question_id)


def vote(request, question_id):
    return HttpResponse('You are voting on question %s.' % question_id)

home/templates/home/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#F8F9FA">
    <link rel="manifest" href="{% static 'manifest.json' %}">
    <title>PWA Demo</title>
</head>

<body class="layout-navbar-fixed sidebar-collapse" style="height: auto;">
    <div class="wrapper">
        <!-- Begin Navbar -->
        <nav class="main-header navbar navbar-expand navbar-black navbar-dark">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
            <li class="nav-item d-none d-sm-inline-block">
                <a href="#" class="nav-link">Home</a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a href="#" class="nav-link">Contact</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Help
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">FAQ</a>
                <a class="dropdown-item" href="#">Support</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Contact</a>
                </div>
            </li>
            </ul>

            <!-- SEARCH FORM -->
            <form class="form-inline ml-3">
            <div class="input-group input-group-sm">
                <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
                </div>
            </div>
            </form>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
            <!-- Messages Dropdown Menu -->
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-comments"></i>
                <span class="badge badge-danger navbar-badge">3</span>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                    <img src="{% static 'libs/AdminLTE-3.0.5/dist/img/user1-128x128.jpg' %}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                    <div class="media-body">
                        <h3 class="dropdown-item-title">
                        Brad Diesel
                        <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                        </h3>
                        <p class="text-sm">Call me whenever you can...</p>
                        <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                    </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                    <img src="{% static 'libs/AdminLTE-3.0.5/dist/img/user8-128x128.jpg' %}" alt="User Avatar" class="img-size-50 img-circle mr-3">
                    <div class="media-body">
                        <h3 class="dropdown-item-title">
                        John Pierce
                        <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                        </h3>
                        <p class="text-sm">I got your message bro</p>
                        <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                    </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                    <img src="{% static 'libs/AdminLTE-3.0.5/dist/img/user3-128x128.jpg' %}" alt="User Avatar" class="img-size-50 img-circle mr-3">
                    <div class="media-body">
                        <h3 class="dropdown-item-title">
                        Nora Silvester
                        <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                        </h3>
                        <p class="text-sm">The subject goes here</p>
                        <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                    </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
                </div>
            </li>
            <!-- Notifications Dropdown Menu -->
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">15</span>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-header">15 Notifications</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-envelope mr-2"></i> 4 new messages
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-users mr-2"></i> 8 friend requests
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-file mr-2"></i> 3 new reports
                    <span class="float-right text-muted text-sm">2 days</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button"><i
                    class="fas fa-th-large"></i></a>
            </li>
            </ul>
        </nav>
        <!-- End Navbar -->

        <!-- Begin Content -->
        <div id="content" class="content-wrapper">
            {% block content %}{% endblock %}
        </div>
        <!-- End Content -->
    </div>

    <footer class="main-footer">
        <strong>Copyright © 2014-2019 <a href="#">AdminLTE.io</a>.</strong>
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
          <b>Version</b> 3.0.3
        </div>
    </footer>

    <script src="{% static 'home/dist/bundle.js' %}"></script>
    <script>
        if ('serviceWorker' in navigator) {
            window.addEventListener('load', (event) => {
                navigator.serviceWorker.register('{% url "service_worker" %}').then((reg) => {
                    // registering worked
                    console.log('Registration succeeded. Scope is ' + reg.scope);
                }).catch((error) => {
                    // registration failed
                    console.log('Registration failed with ' + error);
                });
            });
        }
    </script>
</body>
</html>

home/templates/home/index.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1 class="m-0 text-dark">Dashboard v3</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Dashboard v3</li>
        </ol>
        </div><!-- /.col -->
    </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<div class="content">
    <div class="container-fluid">
    <div class="row">
        <div class="col-lg-6">
        <div class="card">
            <div class="card-header border-0">
            <div class="d-flex justify-content-between">
                <h3 class="card-title">Online Store Visitors</h3>
                <a href="javascript:void(0);">View Report</a>
            </div>
            </div>
            <div class="card-body">
            <div class="d-flex">
                <p class="d-flex flex-column">
                <span class="text-bold text-lg">820</span>
                <span>Visitors Over Time</span>
                </p>
                <p class="ml-auto d-flex flex-column text-right">
                <span class="text-success">
                    <i class="fas fa-arrow-up"></i> 12.5%
                </span>
                <span class="text-muted">Since last week</span>
                </p>
            </div>
            <!-- /.d-flex -->

            <div class="position-relative mb-4"><div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div>
                <canvas id="visitors-chart" height="200" style="display: block; width: 489px; height: 200px;" width="489" class="chartjs-render-monitor"></canvas>
            </div>

            <div class="d-flex flex-row justify-content-end">
                <span class="mr-2">
                <i class="fas fa-square text-primary"></i> This Week
                </span>

                <span>
                <i class="fas fa-square text-gray"></i> Last Week
                </span>
            </div>
            </div>
        </div>
        <!-- /.card -->

        <div class="card">
            <div class="card-header border-0">
            <h3 class="card-title">Products</h3>
            <div class="card-tools">
                <a href="#" class="btn btn-tool btn-sm">
                <i class="fas fa-download"></i>
                </a>
                <a href="#" class="btn btn-tool btn-sm">
                <i class="fas fa-bars"></i>
                </a>
            </div>
            </div>
            <div class="card-body table-responsive p-0">
            <table class="table table-striped table-valign-middle">
                <thead>
                <tr>
                <th>Product</th>
                <th>Price</th>
                <th>Sales</th>
                <th>More</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                <td>
                    <img src="{% static 'libs/AdminLTE-3.0.5/dist/img/default-150x150.png' %}" alt="Product 1" class="img-circle img-size-32 mr-2">
                    Some Product
                </td>
                <td>$13 USD</td>
                <td>
                    <small class="text-success mr-1">
                    <i class="fas fa-arrow-up"></i>
                    12%
                    </small>
                    12,000 Sold
                </td>
                <td>
                    <a href="#" class="text-muted">
                    <i class="fas fa-search"></i>
                    </a>
                </td>
                </tr>
                <tr>
                <td>
                    <img src="{% static 'libs/AdminLTE-3.0.5/dist/img/default-150x150.png' %}" alt="Product 1" class="img-circle img-size-32 mr-2">
                    Another Product
                </td>
                <td>$29 USD</td>
                <td>
                    <small class="text-warning mr-1">
                    <i class="fas fa-arrow-down"></i>
                    0.5%
                    </small>
                    123,234 Sold
                </td>
                <td>
                    <a href="#" class="text-muted">
                    <i class="fas fa-search"></i>
                    </a>
                </td>
                </tr>
                <tr>
                <td>
                    <img src="{% static 'libs/AdminLTE-3.0.5/dist/img/default-150x150.png' %}" alt="Product 1" class="img-circle img-size-32 mr-2">
                    Amazing Product
                </td>
                <td>$1,230 USD</td>
                <td>
                    <small class="text-danger mr-1">
                    <i class="fas fa-arrow-down"></i>
                    3%
                    </small>
                    198 Sold
                </td>
                <td>
                    <a href="#" class="text-muted">
                    <i class="fas fa-search"></i>
                    </a>
                </td>
                </tr>
                <tr>
                <td>
                    <img src="{% static 'libs/AdminLTE-3.0.5/dist/img/default-150x150.png' %}" alt="Product 1" class="img-circle img-size-32 mr-2">
                    Perfect Item
                    <span class="badge bg-danger">NEW</span>
                </td>
                <td>$199 USD</td>
                <td>
                    <small class="text-success mr-1">
                    <i class="fas fa-arrow-up"></i>
                    63%
                    </small>
                    87 Sold
                </td>
                <td>
                    <a href="#" class="text-muted">
                    <i class="fas fa-search"></i>
                    </a>
                </td>
                </tr>
                </tbody>
            </table>
            </div>
        </div>
        <!-- /.card -->
        </div>
        <!-- /.col-md-6 -->
        <div class="col-lg-6">
        <div class="card">
            <div class="card-header border-0">
            <div class="d-flex justify-content-between">
                <h3 class="card-title">Sales</h3>
                <a href="javascript:void(0);">View Report</a>
            </div>
            </div>
            <div class="card-body">
            <div class="d-flex">
                <p class="d-flex flex-column">
                <span class="text-bold text-lg">$18,230.00</span>
                <span>Sales Over Time</span>
                </p>
                <p class="ml-auto d-flex flex-column text-right">
                <span class="text-success">
                    <i class="fas fa-arrow-up"></i> 33.1%
                </span>
                <span class="text-muted">Since last month</span>
                </p>
            </div>
            <!-- /.d-flex -->

            <div class="position-relative mb-4"><div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div>
                <canvas id="sales-chart" height="200" style="display: block; width: 489px; height: 200px;" width="489" class="chartjs-render-monitor"></canvas>
            </div>

            <div class="d-flex flex-row justify-content-end">
                <span class="mr-2">
                <i class="fas fa-square text-primary"></i> This year
                </span>

                <span>
                <i class="fas fa-square text-gray"></i> Last year
                </span>
            </div>
            </div>
        </div>
        <!-- /.card -->

        <div class="card">
            <div class="card-header border-0">
            <h3 class="card-title">Online Store Overview</h3>
            <div class="card-tools">
                <a href="#" class="btn btn-sm btn-tool">
                <i class="fas fa-download"></i>
                </a>
                <a href="#" class="btn btn-sm btn-tool">
                <i class="fas fa-bars"></i>
                </a>
            </div>
            </div>
            <div class="card-body">
            <div class="d-flex justify-content-between align-items-center border-bottom mb-3">
                <p class="text-success text-xl">
                <i class="ion ion-ios-refresh-empty"></i>
                </p>
                <p class="d-flex flex-column text-right">
                <span class="font-weight-bold">
                    <i class="ion ion-android-arrow-up text-success"></i> 12%
                </span>
                <span class="text-muted">CONVERSION RATE</span>
                </p>
            </div>
            <!-- /.d-flex -->
            <div class="d-flex justify-content-between align-items-center border-bottom mb-3">
                <p class="text-warning text-xl">
                <i class="ion ion-ios-cart-outline"></i>
                </p>
                <p class="d-flex flex-column text-right">
                <span class="font-weight-bold">
                    <i class="ion ion-android-arrow-up text-warning"></i> 0.8%
                </span>
                <span class="text-muted">SALES RATE</span>
                </p>
            </div>
            <!-- /.d-flex -->
            <div class="d-flex justify-content-between align-items-center mb-0">
                <p class="text-danger text-xl">
                <i class="ion ion-ios-people-outline"></i>
                </p>
                <p class="d-flex flex-column text-right">
                <span class="font-weight-bold">
                    <i class="ion ion-android-arrow-down text-danger"></i> 1%
                </span>
                <span class="text-muted">REGISTRATION RATE</span>
                </p>
            </div>
            <!-- /.d-flex -->
            </div>
        </div>
        </div>
        <!-- /.col-md-6 -->
    </div>
    <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /.content -->
{% endblock %}

polls/templates/polls/details.html
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }}</li>
    {% endfor %}
</ul>

polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<h1>Polls App</h1>
{% if question_list %}
    <ul>
        {% for question in question_list %}
            <li>
                <a href="{% url 'detail' question.id %}">{{ question.question_text }}</a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No poll is avaible.</p>
{% endif %}